---
name: greenplum
director_uuid: a15be380-3d15-4d8b-84ac-dcb5bae9760e
release:
  name: cf-greenplum
  version: latest

compilation:
  workers: 2
  cloud_properties:
    ram: 8192
    disk: 8096
    cpu: 4
  network: default
  reuse_compilation_vms: true 

update:
  canaries: 1
  canary_watch_time: 3000 - 180000
  update_watch_time: 3000 - 180000
  max_in_flight: 2
  max_errors: 1

networks:
 - name: default
   subnets:
   - range: 10.68.26.0/24
     gateway: 10.68.26.1
     dns:
     - 10.103.42.51
     static:
     - 10.68.26.41
     - 10.68.26.42
     - 10.68.26.43
     reserved:
     - 10.68.26.2-10.68.26.40
     - 10.68.26.50-10.68.26.127
     cloud_properties:
      name : VM Network

resource_pools:
 - name: rp1
   network: default
   size: 10
   stemcell:
    name: bosh-vsphere-esxi-centos
    version: 2579
   cloud_properties:
    ram: 16500
    disk: 4096
    cpu: 2
   env:
    bosh:
      password: $6$2f6qtRfO$oJOeKk/ZDNb7PWnvMiXDC/HstKiLiZCBHP32KHFVeM9rXgs4W/JJiI4a/eHoddhxJzorLYgi2JUQiOKxZko4M.
      # c1oudc0w - password generated using mkpasswd -m sha-512

jobs:
 - name: master
   template: master
   instances: 1
   resource_pool: rp1
   persistent_disk: 4096
   properties:
     host: 10.68.26.41
   networks:
   - name: default
     static_ips:
     - 10.68.26.41

 - name: segment
   template: segment
   instances: 2
   resource_pool: rp1
   persistent_disk: 4096
   properties:
     hosts: 10.68.26.42,10.68.26.43
   networks:
   - name: default
     static_ips:
     - 10.68.26.42-10.68.26.43

properties:
  master:
    host: 
     - 10.68.26.41
  segment:
    hosts: 
     - 10.68.26.42
     - 10.68.26.43
  networks:
    cluster: default
